swagger: "2.0"
info:
  version: "1.0.0"
  title: "RSSchool API"
host: "localhost:3000"
schemes:
- "http"
paths:
  /health:
    get:
      description: "Returns service health status"
      responses:
        200: 
          description: |-
            200 response
  /course/{id}:
    get:
      responses:
        200: 
          description: |-
            200 response
      parameters:
        - name: id
          in: path
          description: Course Id
          required: true
          type: string
  /user/profile:
    get:
      responses:
        200: 
          description: |-
            200 response
  /user/feed:
    get:
      responses:
        200: 
          description: |-
            200 response
    